//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordloadCollegeTeachersDll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicDisciplines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicDisciplines()
        {
            this.Specialties = new HashSet<Specialties>();
        }
    
        public int academic_ID { get; set; }
        public int ID_Disciplines { get; set; }
        public string Name_discipline { get; set; }
        public Nullable<int> Hours_theory { get; set; }
        public Nullable<int> Hours_practice { get; set; }
        public Nullable<int> Hours_independent { get; set; }
        public Nullable<int> Hours_coursework { get; set; }
        public Nullable<int> Number_term { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialties> Specialties { get; set; }
    }
}
