//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordloadCollegeTeachersDll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int ID { get; set; }
        public int specialties_id { get; set; }
        public string Name_group { get; set; }
        public string Form_education { get; set; }
        public string Budget { get; set; }
    
        public virtual Specialties Specialties { get; set; }
    }
}
